# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eabd7684a5921c17b4226a0bd062a8bb134f91f682ab4121e906fe29fdd439a66c277081719fdaab110a5e23bceaab764de402cc0417362a952cdb695b921cc5

test:
  secret_key_base: 29749389f84018c162ef9835622130fbd3acc63a82f2c9dbfd3d7fbcb2c3994ecd2a1f84e5de9b4cd8150d806fa34170433cf77976bb3dac232d0644265c37d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
